/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as FieldNotesRouteImport } from './routes/field-notes'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicationsSlugRouteImport } from './routes/publications_.$slug'
import { Route as FieldNotesSlugRouteImport } from './routes/field-notes_.$slug'

const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldNotesRoute = FieldNotesRouteImport.update({
  id: '/field-notes',
  path: '/field-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsSlugRoute = PublicationsSlugRouteImport.update({
  id: '/publications_/$slug',
  path: '/publications/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldNotesSlugRoute = FieldNotesSlugRouteImport.update({
  id: '/field-notes_/$slug',
  path: '/field-notes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/field-notes': typeof FieldNotesRoute
  '/impact': typeof ImpactRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/field-notes/$slug': typeof FieldNotesSlugRoute
  '/publications/$slug': typeof PublicationsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/field-notes': typeof FieldNotesRoute
  '/impact': typeof ImpactRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/field-notes/$slug': typeof FieldNotesSlugRoute
  '/publications/$slug': typeof PublicationsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/field-notes': typeof FieldNotesRoute
  '/impact': typeof ImpactRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/field-notes_/$slug': typeof FieldNotesSlugRoute
  '/publications_/$slug': typeof PublicationsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/field-notes'
    | '/impact'
    | '/publications'
    | '/research'
    | '/field-notes/$slug'
    | '/publications/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/field-notes'
    | '/impact'
    | '/publications'
    | '/research'
    | '/field-notes/$slug'
    | '/publications/$slug'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/field-notes'
    | '/impact'
    | '/publications'
    | '/research'
    | '/field-notes_/$slug'
    | '/publications_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactUsRoute: typeof ContactUsRoute
  FieldNotesRoute: typeof FieldNotesRoute
  ImpactRoute: typeof ImpactRoute
  PublicationsRoute: typeof PublicationsRoute
  ResearchRoute: typeof ResearchRoute
  FieldNotesSlugRoute: typeof FieldNotesSlugRoute
  PublicationsSlugRoute: typeof PublicationsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-notes': {
      id: '/field-notes'
      path: '/field-notes'
      fullPath: '/field-notes'
      preLoaderRoute: typeof FieldNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications_/$slug': {
      id: '/publications_/$slug'
      path: '/publications/$slug'
      fullPath: '/publications/$slug'
      preLoaderRoute: typeof PublicationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-notes_/$slug': {
      id: '/field-notes_/$slug'
      path: '/field-notes/$slug'
      fullPath: '/field-notes/$slug'
      preLoaderRoute: typeof FieldNotesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactUsRoute: ContactUsRoute,
  FieldNotesRoute: FieldNotesRoute,
  ImpactRoute: ImpactRoute,
  PublicationsRoute: PublicationsRoute,
  ResearchRoute: ResearchRoute,
  FieldNotesSlugRoute: FieldNotesSlugRoute,
  PublicationsSlugRoute: PublicationsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
